### ISSUE TITLE
能发一份资源文件到我的邮箱么

### ISSUE THREAD

**Issue by LaiZhou** [Deali-Axy/CrazyAlpha#2]
想把这个游戏改进下给小朋友玩，资源文件单独发我可以么，hhlai1990@gmail.com, 谢谢。

**Comment by Deali-Axy** [comment]
可以，使用遵循 GPL v2 开源协议即可

**Comment by LaiZhou** [comment]
可以run了，谢谢。

DealiAxy <notifications@github.com> 于2020年2月10日周一 下午6:43写道：
